from bson import ObjectId
import json


class Basis(object):
    def __init__(self, SchemaID, Lid, DmnID):  # chizaye base k domain mikhad bahash kar kone
        self.Lid = Lid
        self.SchemaID = SchemaID
        self.DmnID = DmnID


class Core(Basis):
    def __init__(self, name, usedforid, group, SchemaID, Lid, DmnID):
        super().__init__(SchemaID, Lid, DmnID)

        # attribute hayi k tamame schema ha darand:
        self.name = name
        self.usedforid = usedforid
        self.Group = group
        self.Cat = []
        self.imageurl_small = ''
        self.imageurl_med = ''
        self.imageurl_large = ''


class schema(Core):
    def __init__(self, name, usedforid, group, SchemaID, Lid, DmnID):
        super().__init__(name, usedforid, group, SchemaID, Lid, DmnID)
        with open('schema.js') as f:
            self.data = json.load(f)

    def return_data(self):
        result = {}
        _schema = [
            "field_name",
            "Hotel Name",
            "star rating",
            "Accommodation",
            "Hotel",
            "Motel",
            "Inn",
            "Guest house",
            "Cottage",
            "Villa",
            "Apartment",
            "House boat",
            "Ryokan",
            "Tree house",
            "Riad",
            "Over water accommodation",
            "Apart-hotel",
            "Condominium resort",
            "Caravan Park",
            "Country House",
            "Pension",
            "Safari / Tentalow",
            "Palace",
            "Agri tourism",
            "Camping",
            "Native residence",
            "Rural Residence",
            "Forest Resorts",
            "location",
            "in town",
            "Countryside",
            "Seaside Resort",
            "Island Resort",
            "mountain",
            "jungle",
            "view",
            "forest",
            "Mountains",
            "Sea",
            "Lake",
            "Monument",
            "City",
            "Garden",
            "Courtyard",
            "Pool",
            "Beach",
            "River",
            "Water",
            "ocean",
            "Desert",
            "Various Views",
            "Park",
            "Nature",
            "green space",
            "sport court",
            "stadium",
            "Island",
            "Plain",
            "Road",
            "Bay",
            "harbor",
            "Waterpark",
            "Parking Area",
            "Atrium",
            "No View",
            "Number of Rooms",
            "number of floors",
            "hotel facilities",
            "Pets Allowed",
            "night club",
            "massage",
            "beauty salon",
            "kid club",
            "Children''s Special Program",
            "laundry",
            "shopping center",
            "ATM",
            "banquet",
            "tour/ticket assistance",
            "Restaurant",
            "bar",
            "food serverd in the room",
            "Currency Exchange",
            "Safety Boxes",
            "Elevator",
            "24-hour Check- In",
            "24-hour room service",
            "Coffee / Tea In Lobby",
            "Family Room",
            "Guard",
            "transfer airport",
            "Mobile rental/cell phone",
            "Coffee shop",
            "Computer Rental",
            "Computer Station",
            "Concierge Service",
            "Conferance salon",
            "Garden",
            "Gift Shop",
            "Convenience Store",
            "medical assistance available",
            "Wake-up calls",
            "multilingual staff",
            "Dining room",
            "safe room",
            "Luggage storage",
            "newspapers in lobby",
            "Electronic/magnetic keys",
            "Express check-out",
            "Express check-in",
            "Television in lobby",
            "Microwave in lobby",
            "Porter/bellhop",
            "Security guard",
            "Fireplace in lobby",
            "Picnic area",
            "Barber",
            "Translation services",
            "Electronic check-out",
            "internet point",
            "Children playground",
            "Sandwich shop",
            "car rental",
            "poolside bar",
            "lounge bar",
            "shared lounge/TV area",
            "Sun terrace",
            "meeting facilities",
            "Meeting room",
            "Fax/photocopying",
            "locker",
            "buffet",
            "free buffet",
            "library",
            "Roof terrace",
            "concession stand beside pool",
            "Free local calls",
            "pool umbrella",
            "honeymoon suite",
            "Special Diet Meals (upon request)",
            "pool Slippers",
            "Soundproof Room",
            "VIP room",
            "Shoe polish machine",
            "vending machine",
            "Packed lunches",
            "Porter",
            "Yard",
            "skin health and beauty services",
            "Magic",
            "Green space",
            "exhibition",
            "fire alarm system",
            "amphitheatre",
            "Private check-in and checkout",
            "alarm clock",
            "newsstand",
            "pray room",
            "postbank",
            "post",
            "toilet",
            "evening meal",
            "traditional coffeehouse",
            "auxiliary power supply",
            "emergency exit door",
            "fire escape stairs",
            "power switch",
            "central antenna",
            "Multi purpose halls",
            "key maker machine",
            "squat toilet",
            "scurity camera",
            "VoIP phone system",
            "ceremonial hall",
            "moped rental",
            "Shuttle service",
            "live music in lobby",
            "Taxi service",
            "fire extinguisher",
            "Congress hall",
            "CIP services",
            "Barbecue",
            "Roof garden",
            "Bicycle rental",
            "Wedding services",
            "Pool sun loungers",
            "Entertainment staff",
            "entertainment",
            "Chapel/shrine",
            "Circus",
            "pool towel",
            "Picnic space",
            "smoke detector",
            "Condominium Unit",
            "Different Building",
            "Private Entrance",
            "casino",
            "cinema",
            "Theater",
            "Movie Theater",
            "Art Gallery",
            "Museum",
            "Lobby",
            "Lounge",
            "Lanai",
            "outdoor patio",
            "park",
            "Traditional restaurant",
            "Maid Service",
            "Business center",
            "Pets Not Allowed",
            "Family Activities",
            "Trouser press",
            "Snack Bar",
            "Dining guide",
            "Appetizer",
            "evening meal",
            "Free Snack",
            "Grocery Stores",
            "Foodstuffs Shopping Service",
            "Credits for food and drink",
            "Discount for food and drink",
            "European Plan",
            "Chauffer",
            "Interpreter",
            "maidroom",
            "lesbian friendly",
            "gay friendly",
            "Business Room",
            "Boardroom Table",
            "Connecting Rooms",
            "Adjoining rooms",
            "Allergy-free room",
            "Exterior Corridors",
            "Interior Corridors",
            "Spiral Staircase",
            "Sporting Goods Shop",
            "Sports locker rooms",
            "Pantry",
            "Safe",
            "FAX",
            "Computer",
            "ISDN",
            "Locker Rooms",
            "Water Transportation",
            "Background music",
            "Secretarial Services",
            "motorcycle rentals",
            "Boat Rentals",
            "International calls",
            "LAN access",
            "Secured Access Internet",
            "Outside Access",
            "High chair",
            "High chair Rentals",
            "Penthouse",
            "Shared bathroom",
            "Basement",
            "Jogging Track",
            "Welcome gift",
            "Activity Table",
            "Sky Deck Access",
            "24- Hour Maintenance",
            "NO Wheelchair accessible",
            "Trash Service",
            "Pet bowls",
            "Pet basket",
            "Balcony on water",
            "Bench",
            "No Suite",
            "firepit",
            "Lake Access",
            "non-poolside",
            "room type",
            "One Bed",
            "Two Beds",
            "triple room",
            "Quadruple Room",
            "Suite",
            "one Bedroom Suite",
            "two Bedroom Suite",
            "three Bedroom Suite",
            "four Bedroom Suite",
            "Duplex Suite",
            "Parlor Suite",
            "Junior Suite",
            "Fiesta Suite",
            "Suite with Loft Area",
            "King room",
            "Tower Room",
            "Senior Room",
            "Environmental Room",
            "Ground Floor room",
            "shared room",
            "Cabana Room",
            "queen room",
            "Standard Room",
            "Deluxe Room",
            "Superior room",
            "Executive Room",
            "studio room",
            "Hollywood Twin Room",
            "room facilities",
            "Iron and Pressboard",
            "Direct phone",
            "Tea Maker",
            "Safety Boxes",
            "Mini-bar",
            "Coffee / Tea In room",
            "bathroom",
            "extera bed",
            "window opens",
            "refrigerator",
            "Clock radio",
            "Blackout drapes/curtains",
            "Cribs",
            "Voice mail",
            "Microwave",
            "Makeup/shaving mirror",
            "bottled water",
            "Extra towels/bedding",
            "Kitchen",
            "DVD and CD Player",
            "Cookware, dishware, and utensils",
            "Sofa bed",
            "Sewing Machine",
            "Dishwasher",
            "Separate living room",
            "Fireplace in Room",
            "Blender",
            "Separate bedroom",
            "bidet",
            "balcony",
            "BBQ facilities",
            "locker",
            "Desk",
            "toiletries",
            "newspaper in room",
            "extera mattress",
            "laptop",
            "Radio",
            "system IPTV",
            "video",
            "washing machine",
            "Room service (during limited hours)",
            "coffee maker",
            "fire extinguisher",
            "Card lock",
            "Closet",
            "Pillow menu",
            "Slippers",
            "toilet",
            "squat toilet",
            "Partially open bathroom",
            "Stovetop",
            "Oven",
            "Children television networks",
            "IPod docking station",
            "mp3 docking station",
            "Mosquito net",
            "table",
            "chair",
            "carpet",
            "fridge",
            "Water cooler",
            "makeup table",
            "Mirror",
            "Shoes holder",
            "Cosmetic kit",
            "bedside lamp",
            "Separate food room",
            "dressing room",
            "Massage",
            "full appliances",
            "Room service",
            "Climate Control",
            "No Living Room",
            "Kettle",
            "Electric Kettle",
            "drink in room",
            "Wet Bar",
            "Chocolate",
            "cookie",
            "dinning room",
            "Dining Table Chairs",
            "Table and chairs",
            "balcony desk",
            "Ergonomic Chair",
            "Recliner",
            "Loveseat",
            "Hamper",
            "curtain",
            "Chair with Ottoman",
            "activity table",
            "Patio",
            "Sofa",
            "furniture in terrace",
            "double sofa bed",
            "L- Shape Sofa Bed",
            "Sofabed for child",
            "Mattress",
            "Pillow top Mattress",
            "futon",
            "Massage chair",
            "Prayer mats",
            "Cordless Phone",
            "Full Kitchen",
            "Toaster",
            "Cabinets",
            "Vanities",
            "Sinks",
            "Weight Scale",
            "Kitchen Scale",
            "No Refrigerator",
            "hot plate",
            "combine living area",
            "No Window",
            "Panoramic Window",
            "Soundproof Windows",
            "double glazing window",
            "triple glazing window",
            "Bay Window",
            "french door",
            "sleepwear",
            "Robe",
            "bathrobe",
            "Linens",
            "Turndown service",
            "Basket Clothes",
            "Duvet Covers",
            "clothes rack",
            "Work Area",
            "Work desk",
            "Water Filtration",
            "Air Filtration",
            "iron",
            "Hair straighteners",
            "desk hair dryer",
            "Desk Lamp",
            "Towel menu",
            "Luxury linen",
            "Humidifier",
            "Adapter",
            "Modem",
            "Media Hub",
            "Instant hot water",
            "Wall clock",
            "Door Bell",
            "Sewing kit",
            "Shoeshine kit",
            "Office supplies",
            "Pen",
            "note",
            "High ceilings",
            "Vaulted Ceiling",
            "Carpeted",
            "wooden/parquet flooring",
            "vinyl flooring",
            "Xbox",
            "game console",
            "Playstation",
            "Sega Game",
            "iPad",
            "amplifier",
            "Printer",
            "In-Room Video Games",
            "In-Room Pay Video Games",
            "Speaker Phone",
            "Telephone Jack Adapter",
            "Modem Port",
            "Data Port",
            "power outlet",
            "electrical outlet desk",
            "emergency call button",
            "A/V Equipment",
            "Bose  Wave  Sound  System",
            "Remote Control TV",
            "Computer Hookup",
            "Satellite radio",
            "Wireless keyboard",
            "Electronic Door Lock",
            "Plug computer",
            "Entertainment center",
            "Answering Machine",
            "extended bathroom",
            "Hot tub In Room",
            "raised toilet seat",
            "bed type",
            "Single Bed",
            "Double bed",
            "twin beds",
            "double extera long",
            "twin extera long",
            "Rollaway Bed",
            "Wall bed",
            "Bunk beds",
            "triple bed",
            "queen bed",
            "King bed",
            "Murphy bed",
            "Sleep Number Bed",
            "Bed with canopy",
            "Bed height",
            "Pillow material",
            "feather",
            "glass wool",
            "foam",
            "Cosmetic services",
            "Full body massage",
            "Hand massage",
            "Head massage",
            "Couples massage",
            "Foot massage",
            "Neck massage",
            "Back massage",
            "Hair styling",
            "Hair colouring",
            "Hair cut",
            "Manicure",
            "Pedicure",
            "Make up services",
            "Waxing services",
            "Hair treatments",
            "Facial treatments",
            "Bathroom",
            "shower",
            "Shower Room",
            "Tub",
            "Hairdryer",
            "Bathroom phone",
            "Telephone shower",
            "Shower Massage",
            "Walk In Shower",
            "roll in showers",
            "hand held shower",
            "power shower",
            "Whirlpool",
            "two Person Whirlpool",
            "Hydromassage Bathtubs",
            "therapeutic tub",
            "Bathtub Jets",
            "Grab bars",
            "Curved Shower Rod",
            "shower bench",
            "Shower Clock Radio",
            "Heated Bathroom Floor",
            "TV",
            "Cable",
            "Satellite",
            "Normal",
            "N/A",
            "Flat-panel",
            "LCD",
            "HD",
            "LED",
            "Digital",
            "Free channels",
            "Plasma",
            "FULL HD",
            "Interactive TV",
            "360 degree rotating tv",
            "country",
            "city",
            "holding company",
            "TV channels",
            "Humorous",
            "Religious",
            "news",
            "Wildlife",
            "show",
            "Cartoons",
            "Documentary",
            "movie",
            "Sports",
            "Music",
            "Historical",
            "medical",
            "Educational",
            "international",
            "children''s programs",
            " Adult Channel",
            "Adult Channel Lock",
            "No Adult Channels offered ",
            "Additional charge",
            "internet services",
            "Wireless",
            "free",
            "surcharge",
            "in the room",
            "N/A",
            "Free wired high-speed Internet",
            "ventilation system",
            "Gaseous",
            "Air conditioning",
            "Heating",
            "Air-conditioned public areas",
            "Ceiling fan",
            "water air cooler",
            "air conditioner",
            "Fan coil",
            "Chiller",
            "mini Chiller",
            "central heating package",
            "No Air Conditioning",
            "Cooling",
            "sport and entertainment",
            "Rock Climbing",
            "children pool",
            "dry Sauna",
            "Steam Sauna",
            "Wet Sauna",
            "Sudatorium",
            "Squash",
            "Motorized water sports",
            "Non-motorized water sports",
            "Ski Resort",
            "Climbing",
            "Water sports",
            "forest trekking",
            "Outdoor Pool",
            "indoor pool",
            "Private Pool",
            "Private Jacuzzi",
            "Public Jacuzzi",
            "health club",
            "fitness center",
            "Spa",
            "Tennis course",
            "Golf course",
            "Beachfront",
            "game room",
            "Billiards",
            "game",
            "Water park",
            "Yoga class",
            "Solarium",
            "water slide",
            "mini golf course",
            "table tennis",
            "diving",
            "Paragliding",
            "bicycle track",
            "playground",
            "dart",
            "Boating",
            "Pilates",
            "Fishing",
            "Scooter",
            "Water skiing",
            "horse riding",
            "Kayaking",
            "Motor boating",
            "surfing",
            "Karaoke",
            "water ball",
            "Aerobics",
            "Bowling",
            "Basketball Court",
            "Badminton court",
            "Football court",
            "Handball court",
            "ice skating",
            "Table Football",
            "grass hockey",
            "ice Hockey",
            "Indoor hockey",
            "Snowmobiling",
            "Snowboarding",
            "Snowshoeing",
            "skate resort",
            "Board games",
            "card games",
            "Seasonal Pool",
            "Lap Pool",
            "parasailing",
            "dance class",
            "Amusement Park",
            "Shooting",
            "Tubing on water",
            "Tubing on snow",
            "Volleyball Court",
            "hammam",
            "Sleigh Rides",
            "Dog Sledding",
            "Ballooning",
            "Skiing jet",
            "Sailing",
            "Zip  Line",
            "Hunting",
            "salt room",
            "Lazy  River",
            "Sledding",
            "Bird Watching",
            "Whale Watching",
            "Boogie Boarding",
            "Snowshoeing",
            "Ski Lessons",
            "Credit for game / race",
            "Special Features",
            "babysitting services",
            "Business Meetings",
            "Helicopter Pad",
            "facility Beach",
            "Sunbathing",
            "Beach bar",
            "Coastal Cottage",
            "Beach towels",
            "Beach umbrellas",
            "sun chair",
            "beach cabanas",
            "beach slippers",
            "Beach Club",
            "shuttle",
            "Beach",
            "playground",
            "park",
            "Ski",
            "passenger terminal",
            "different areas",
            "Shopping center",
            "facilities for disabled",
            "Associated Services for the Blind and Visually Impaired",
            "Facilities for deaf and hearing impaired people",
            "Handicapped parking",
            "Special facilities for disabled",
            "Bathroom with flat floor",
            "shower seats",
            "wheelchair",
            "Special lifts for the disabled",
            "disabled access ramp",
            "Disabled Room",
            "handicapped toilet",
            "handicap bathroom",
            "transfer bench",
            "handicap closet",
            "hearing impaired phone",
            "Smoking",
            "Smoking Area",
            "Designated smoking area",
            "Smoking upon request",
            "Smoke Free",
            "No smoking",
            "Non-Smoking Rooms",
            "parking",
            "parking",
            "Self parking",
            "parking on Outdoor",
            "Parking nearby",
            "Secure parking",
            "on-street parking",
            "reservation is needed",
            "valet",
            "motorcycle parking",
            "Underground  Parking",
            "Covered Parking",
            "rear parking access",
            "Parking (with charge)",
            "housekeeping",
            "Daily",
            "Housekeeping - once per stay",
            "Housekeeping - 2 days per week",
            "Housekeeping - 3 days per week",
            "Housekeeping - 4 days per week",
            "Housekeeping - 5 days per week",
            "Housekeeping - 6 days per week",
            "limited cleaning",
            "breakfast service",
            "breakfast",
            "breakfast with buffet",
            "breakfast in lobby",
            "breakfast in room",
            "N/A",
            "Lunch service",
            "Lunch",
            "Lunch with buffet",
            "Lunch in lobby",
            "Lunch in room",
            "N/A",
            "dinner service",
            "dinner",
            "dinner with buffet",
            "dinner in lobby",
            "dinner in room",
            "N/A",
            "year built",
            "number of buildings/towers",
            "number of resturantS",
            "number of bars",
            "Number of coffee shops",
            "number of Conference hall",
            "number of meeting room",
            "meeting facilites size",
            "Room Dimensions",
            "number of indoor pools",
            "number of outdoor pools",
            "Number of pool bar",
            "Number of tennis court",
            "Maximum number of pets per room",
            "pet maximum weight",
            "Minimum check-in age is",
            "Minimum guest age is",
            "check in",
            "check out",
            "Voltage",
            "110",
            "220",
            "Original Photo",
            "Staff languages",
            "payment type",
            "Cash Deposit",
            "Debit cards",
            "Separate Line Billing",
            "accessible Debit cards",
            "visa",
            "MasterCard",
            "AmericanExpress",
            "JCB international",
            "Discover",
            "visa electron",
            "maestro",
            "delta",
            "solo",
            "diners club",
            "debit",
            "bank card",
            "euro check",
            "UnionPay",
            "euro mastercard",
            "carte bleue",
            "bancontact",
            "switch",
            "carte blanche",
            "nicos",
            "uc",
            "cartasi",
            "cabal",
            "red compra",
            "hipercard",
            "eccard",
            "bc card",
            "paypal",
            "payplug",
            "postepay",
            "pagseguro",
            "mpesa",
            "bankaxept",
            "western union",
            "GPS",
            "Address",
            "Postal Code",
            "Phone",
            "Fax",
            "Website",
            "Email",
            "",
            "GIATA",
            "Link",
            "EANHotelID"
        ]
        hotel_collection = {
            "_id": ObjectId("5ba9fc558b9f893966b68e8e"),
            "Address": "Scanderbeg Square, Build. 8 , Entr. 1street Tirana",
            "Category": 4,
            "CityId": 8,
            "CountryId": 6,
            "Email": "HOTEL@HOTELTIRANA.COM.AL",
            "Fax": " 355 42 234188",
            "HotelId": 1807973,
            "LastUpdateDate": "/Date(1435559006443+0300)/",
            "Lat": 41.329645,
            "Lon": 19.818595,
            "Phone": " 355 42 234185",
            "Zipcode": "",
            "hoteldetail": {
                "HotelId": "1807973",
                "HotelName": "Tirana International Hotel Conference Centre",
                "HotelAddress": "Scanderbeg Square, Build. 8 , Entr. 1street Tirana",
                "HotelChainId": "0",
                "CountryId": "6",
                "CityId": "8",
                "CategoryId": "4",
                "Latitude": "41.329645",
                "Longitude": "19.818595",
                "HotelFacilityIds": {
                    "int": [
                        "78",
                        "842",
                        "334",
                        "842",
                        "36",
                        "10616",
                        "165",
                        "54",
                        "343",
                        "49",
                        "4",
                        "78",
                        "58",
                        "261",
                        "313",
                        "20",
                        "890",
                        "335",
                        "15",
                        "10616",
                        "115"
                    ]
                },
                "RoomFacilityIds": {
                    "int": [
                        "6",
                        "16",
                        "17",
                        "7",
                        "8",
                        "9",
                        "10",
                        "11",
                        "18",
                        "26",
                        "14",
                        "32",
                        "19",
                        "31",
                        "20",
                        "15",
                        "21",
                        "22",
                        "23",
                        "24",
                        "2",
                        "4",
                        "797"
                    ]
                },
                "ChildAgeMin": "0",
                "ChildAgeMax": "0",
                "ConstructedYear": "0",
                "RenovatedYear": "0",
                "TotalRooms": "0",
                "TotalFloors": "0",
                "HotelDesc": "Tirana International Hotel & Conference Centre is one of the most prestigious and largest hotels in Albania on Scanderbeg Square. Tirana International Hotel has always been considered the symbol of the capital. Built during Albania’s isolation years with an imposing socialist architectural style, Tirana International Hotel used to be the tallest building in the country. Furthermore Tirana International Hotel was exclusively used for foreign delegations and tourists, making it intriguing and mysterious for Albanians. In 2001Tirana International Hotel was totally renovated to a four star hotel of international standards by an Italian firm, while still retaining its grandiose past features. Tirana International Hotel has been for years the place for important events in Albania and home to many international business travelers who appreciate Excellence in Service. Since the arrival at the Tirana International Hotel, the cheerful attitude of the employees dedicated to achieve total customer satisfaction make the stay at the Tirana International Hotel an enjoyable experience.",
                "Location": "The hotel is located in Tirana, Albania. It is situated in the commercial centre of the city and is surrounded by shops, bars and restaurants. The hotel is 35 km from the beach and the port of Durres, and Tirana Airport is just 28 km away. The opera house, palace and central bank are located just across the square.",
                "Area": "Airport: Tirana Rinas from K 13.0",
                "Lobby": None,
                "Room": "All of the en suite rooms include a hairdryer, direct dial telephone, minibar, cable TV, radio, safe, plus heating and air conditioning units. All the rooms feature either a double or king-size bed.",
                "Restaurant": None,
                "Exterior": None,
                "HotelPhotos": {
                    "string": [
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/11.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/12.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/13.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/14.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/15.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/16.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/17.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/18.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/19.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/20.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/21.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/22.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/23.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/24.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/25.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/26.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/27.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/28.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/29.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/30.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/31.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/32.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/33.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/34.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/35.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/36.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/37.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/38.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/39.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/40.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/41.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/42.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/43.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/44.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/45.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/46.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/47.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/48.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/49.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/50.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/51.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/52.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/53.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/54.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/55.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/56.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/57.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/58.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/59.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/60.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/61.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/62.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/63.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/64.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/65.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/66.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/67.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/68.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/69.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/70.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/71.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/72.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/73.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/74.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/75.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/76.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/77.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/78.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/79.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/80.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/81.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/82.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/83.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/84.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/85.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/86.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/87.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/88.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/89.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/90.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/91.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/92.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/93.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/94.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/95.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/96.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/97.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/98.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/99.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/100.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/101.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/102.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/103.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/104.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/105.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/106.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/107.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/108.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/109.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/110.jpg",
                        "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/111.jpg"
                    ]
                },
                "RequestIp": "84.241.22.93"
            },
            "giata": {
                "HOTELID": 1807973
            },
            "Hotel Name": "Tirana International Hotel Conference Centre",
            "Minimum check-in age is": "0",
            "GIATA": 87098,
            "Original Photo": [
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/11.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/12.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/13.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/14.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/15.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/16.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/17.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/18.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/19.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/20.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/21.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/22.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/23.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/24.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/25.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/26.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/27.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/28.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/29.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/30.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/31.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/32.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/33.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/34.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/35.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/36.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/37.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/38.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/39.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/40.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/41.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/42.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/43.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/44.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/45.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/46.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/47.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/48.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/49.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/50.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/51.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/52.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/53.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/54.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/55.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/56.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/57.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/58.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/59.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/60.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/61.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/62.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/63.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/64.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/65.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/66.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/67.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/68.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/69.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/70.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/71.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/72.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/73.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/74.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/75.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/76.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/77.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/78.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/79.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/80.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/81.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/82.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/83.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/84.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/85.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/86.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/87.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/88.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/89.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/90.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/91.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/92.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/93.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/94.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/95.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/96.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/97.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/98.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/99.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/100.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/101.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/102.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/103.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/104.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/105.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/106.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/107.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/108.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/109.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/110.jpg",
                "https://i.vanillatours.com/3/7/9/7/0/8/1/1807973/Y/111.jpg"
            ]
        }
        # print(self.data)
        for item in self.data:
            try:
                setattr(self, item['Title'], hotel_collection[item['Title']])
                result.update({item['Title']: hotel_collection[item['Title']]})
                # print(result)
            except:
                result.update({item['Title']: None})

        print('_schema length: ', len(self.data))
        print('result length: ', len(result))
        print('hotel_collection length: ', len(hotel_collection))
        print(result)
        return result


schema('hotel', 0, [], 251, 2, 2452).return_data()
